// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string;

// Basic env checks to fail early in dev if vars are missing
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.warn(
    '[supabase] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. ' +
    'Make sure .env has those values and restart the dev server.'
  );
}

// Protect against SSR / build-time access to localStorage
const authStorage = typeof window !== 'undefined' ? localStorage : undefined;

// Import the supabase client like this:
// import { supabase, testConnection } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: authStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

/**
 * testConnection
 * - Lightweight check using Supabase Auth endpoint + a fetch to the project URL.
 * - Returns an object with ok boolean and details for debugging.
 */
export async function testConnection() {
  try {
    // 1) Try Supabase auth endpoint (safe, requires no signed-in user)
    const { data, error } = await supabase.auth.getSession();
    if (error) {
      return { ok: false, source: 'auth.getSession', error };
    }

    // 2) Try a simple fetch to the project URL (network-level reachability)
    let urlOk = false;
    let urlStatus: number | null = null;
    try {
      const resp = await fetch(SUPABASE_URL, { method: 'GET' });
      urlStatus = resp.status;
      urlOk = resp.ok || resp.status === 404; // some project root endpoints return 404 but server reachable
    } catch (fetchErr) {
      return { ok: false, source: 'fetch', error: fetchErr };
    }

    return { ok: true, urlStatus, data };
  } catch (err) {
    return { ok: false, source: 'unknown', error: err };
  }
}